<?php echo $this->render('layout_header.phtml');?>

<body>
    <div class="logo"><img border="0" width="172" height="93" src="<?php echo IMAGES_URL."/logoBig1.gif";?>" alt=""></div>
    <?php
        $h = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    ?>
<div class="wrapper">
  <script type="text/javascript">
      var BASE_URL = '<?php echo BASE_URL?>';
  </script>

<?php echo $this->layout()->content; ?>
<?php echo $this->render('layout_footer.phtml');?>
